#CONFIG FILE
#TODO

#WHAT IS YOUR SERVER NAME

Name: CASTLERAID

items:
  # Format for items is id:meta:amount:name:price:imgtype:imgpath (Note: imgtype and imgpath are optional. 0 is path, 1 is url)
  weapons:
    - "268:0:1:Wooden Sword:2500:0:textures/items/wood_sword"
    - "272:0:1:Stone Sword:5000:0:textures/items/stone_sword"
    - "267:0:1:Golden Sword:10000:0:textures/items/gold_sword"
    - "283:0:1:Iron Sword:15000:0:textures/items/iron_sword"
    - "276:0:1:Diamond Sword:25000:0:textures/items/diamond_sword"
    - "261:0:1:Bow:2000:0:textures/items/bow_standby"
    - "262:0:1:Arrow:3000:0:textures/items/arrow"
  tools:
    - "278:0:1:Diamond Pickaxe:25000:0:textures/items/diamond_pickaxe"
    - "285:0:1:Golden Pickaxe:15000:0:textures/items/gold_pickaxe"
    - "257:0:1:Iron Pickaxe:20000:0:textures/items/iron_pickaxe"
    - "274:0:1:Stone Pickaxe:5000:0:textures/items/stone_pickaxe"
    - "270:0:1:Wooden Pickaxe:2500:0:textures/items/wood_pickaxe"
  armor:
    -
  blocks:
    -
  specials: [""]
  masks: [""]
